from=./smoker.png
to=textures/gui/container/smoker.png
x=176
y=0
w=14
h=14

interpolate=true

tile.0=0
duration.0=2
tile.1=1
duration.1=2
tile.2=2
duration.2=2
tile.3=3
duration.3=2
tile.4=4
duration.4=2
tile.5=5
duration.5=2
tile.6=6
duration.6=2
